name: MultiCommandBlock
version: 1.12
description: Multi-Line  and Multi-Command  Block for Bukkit Server
authors: [MemoryLeakX, Kryssi79]

main: com.MeLxKry.mcbp.main_MCBP



commands:
  MCB:
    description:  multi Commands
    usage: wenn Fehler
    permission: MCB.use
