name: MultiCommandBlock
version: 0.43
description: Multi-Line  and Multi-Command  Block for Bukkit Server
authors: [MemoryLeakX, Kryssi79]

main: com.MeLxKry.mcbp.main_MCBP



commands:
  mcbTest:
    description:  CommandBlock Test
    usage: wenn Fehler
    permission: mcbTest.use
  MCB:
    description:  multi Commands
    usage: wenn Fehler
    permission: MCB.use
